import * as React from 'react';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import BottomNavigation from '@mui/material/BottomNavigation';
import BottomNavigationAction from '@mui/material/BottomNavigationAction';
import RestoreIcon from '@mui/icons-material/Restore';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ArchiveIcon from '@mui/icons-material/Archive';
import Paper from '@mui/material/Paper';
import List from '@mui/material/List';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemAvatar from '@mui/material/ListItemAvatar';
import ListItemText from '@mui/material/ListItemText';
import Avatar from '@mui/material/Avatar';

function refreshMessages() {
  const getRandomInt = (max) => Math.floor(Math.random() * Math.floor(max));

  return Array.from(new Array(50)).map(
    () => messageExamples[getRandomInt(messageExamples.length)],
  );
}

export default function FixedBottomNavigation() {
  const [value, setValue] = React.useState(0);
  const ref = React.useRef(null);
  const [messages, setMessages] = React.useState(() => refreshMessages());

  React.useEffect(() => {
    ref.current.ownerDocument.body.scrollTop = 0;
    setMessages(refreshMessages());
  }, [value, setMessages]);

  return (
    <Box sx={{ pb: 7 }} ref={ref}>
      <CssBaseline />
      <List>
        {messages.map(({ primary, secondary, person }, index) => (
          <ListItemButton key={index + person}>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={person} />
            </ListItemAvatar>
            <ListItemText primary={primary} secondary={secondary} />
          </ListItemButton>
        ))}
      </List>
      <Paper sx={{ position: 'fixed', bottom: 0, left: 0, right: 0 }} elevation={3}>
        <BottomNavigation
          showLabels
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          <BottomNavigationAction label="Recents" icon={<RestoreIcon />} />
          <BottomNavigationAction label="Favorites" icon={<FavoriteIcon />} />
          <BottomNavigationAction label="Archive" icon={<ArchiveIcon />} />
        </BottomNavigation>
      </Paper>
    </Box>
  );
}

const messageExamples = [
  {
    primary: 'Brunch this week?',
    secondary: "xian zai wo you bing qi lin. wo hen xi huan bing qi lin",
    person: 'https://www.wwe.com/f/styles/gallery_img_l/public/all/2017/01/005_01242017_JohnCena_0450dog--e422a3dd443b43cc1e9abedeafdf283d.jpg',
  },
  {
    primary: 'Birthday Gift',
    secondary: `I'm getting John a 12-pack. And that's the bottom line cuz Stone Cold said so`,
    person: 'https://www.thesportster.com/wp-content/uploads/2020/06/steve-austin-ic-title.jpg',
  },
  {
    primary: 'Fun Fact',
    secondary: 'Licking doorknobs is illegal on other planets',
    person: 'https://th.bing.com/th/id/R.cbfd99d87eb0868c65a2429030d747aa?rik=Kcm%2blOdSAwa0qA&riu=http%3a%2f%2fpngimg.com%2fuploads%2fspongebob%2fspongebob_PNG11.png&ehk=uswZEKSa%2bgS6JvjEasBh589TCL%2f2ZymNiUHCA1yBBFY%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    primary: 'HR Complaint',
    secondary: 'Who you callin Pinhead?',
    person: 'https://th.bing.com/th/id/OIP.-XS9jcAYCN-ChqK4SoUAvAHaHa?rs=1&pid=ImgDetMain',
  },
  {
    primary: "Doctor's Appointment",
    secondary: 'Call an ambulance but not for me. Id like to take this time to apologize to absolutely nobody',
    person: 'https://th.bing.com/th/id/R.06b309fc90e352bf12ea953384b33a7c?rik=c65zKjvMm%2f8EsA&riu=http%3a%2f%2fwww.thefamouspeople.com%2fprofiles%2fimages%2fconor-mcgregor-3.jpg&ehk=FEWFEql9wa4Nsxwfa4jt98e9GeNLxEf4lF9Wcqn4XMk%3d&risl=&pid=ImgRaw&r=0',
  },
  {
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: 'https://i.ytimg.com/vi/LxIuh15hrGE/maxresdefault.jpg',
  },
  {
    primary: 'Summer BBQ',
    secondary: `Do you smell what The Rock is cookin?`,
    person: 'https://th.bing.com/th/id/R.0e09adb835b673f899e0fc7800b5f43b?rik=lP%2fHYoHaKYuJ0g&riu=http%3a%2f%2fthefederalist.com%2fwp-content%2fuploads%2f2016%2f08%2ftherock.jpg&ehk=9ZR71ggsrbkoy%2f3OREP7mb%2fBzoe3mg6tnQywFBssIYk%3d&risl=&pid=ImgRaw&r=0',
  },
];
